instr_extract = {'vegetarian': True,
                 'vegan': False,
                 'glutenFree': True,
                 'dairyFree': True,
                 'veryHealthy': False,
                 'cheap': False,
                 'veryPopular': False,
                 'sustainable': False,
                 'weightWatcherSmartPoints': 29,
                 'gaps': 'no',
                 'lowFodmap': True,
                 'aggregateLikes': 212,
                 'spoonacularScore': 71.0,
                 'healthScore': 13.0,
                 'pricePerServing': 261.94,
                 'extendedIngredients': [{'id': 12006,
                                          'aisle': 'Health Foods',
                                          'image': 'chia-seeds.jpg',
                                          'consistency': 'solid',
                                          'name': 'chia seeds',
                                          'original': '2 tablespoons ground chia seeds (20 grams)',
                                          'originalString': '2 tablespoons ground chia seeds (20 grams)',
                                          'originalName': 'tablespoons ground chia seeds',
                                          'amount': 20.0,
                                          'unit': 'grams',
                                          'meta': [],
                                          'metaInformation': [],
                                          'measures': {'us': {'amount': 0.705,
                                                              'unitShort': 'oz',
                                                              'unitLong': 'ounces'},
                                                       'metric': {'amount': 20.0, 'unitShort': 'g', 'unitLong': 'grams'}}},
                                         {'id': 19904,
                                          'aisle': 'Sweet Snacks',
                                          'image': 'dark-chocolate-pieces.jpg',
                                          'consistency': 'solid',
                                          'name': 'dark chocolate',
                                          'original': '1/3 cup chopped 85% dark chocolate (50 grams)',
                                          'originalString': '1/3 cup chopped 85% dark chocolate (50 grams)',
                                          'originalName': '1/3 cup chopped 85% dark chocolate',
                                          'amount': 50.0,
                                          'unit': 'grams',
                                          'meta': ['dark', '85%', 'chopped'],
                                          'metaInformation': ['dark', '85%', 'chopped'],
                                          'measures': {'us': {'amount': 1.764,
                                                              'unitShort': 'oz',
                                                              'unitLong': 'ounces'},
                                                       'metric': {'amount': 50.0, 'unitShort': 'g', 'unitLong': 'grams'}}},
                                         {'id': 1173,
                                          'aisle': 'Baking',
                                          'image': 'white-powder.jpg',
                                          'consistency': 'solid',
                                          'name': 'egg white powder',
                                          'original': '¼ cup egg-white protein powder (20 grams)',
                                          'originalString': '¼ cup egg-white protein powder (20 grams)',
                                          'originalName': '¼ cup egg-white protein powder',
                                          'amount': 20.0,
                                          'unit': 'grams',
                                          'meta': [],
                                          'metaInformation': [],
                                          'measures': {'us': {'amount': 0.705,
                                                              'unitShort': 'oz',
                                                              'unitLong': 'ounces'},
                                                       'metric': {'amount': 20.0, 'unitShort': 'g', 'unitLong': 'grams'}}},
                                         {'id': 12118,
                                          'aisle': 'Canned and Jarred;Milk, Eggs, Other Dairy',
                                          'image': 'coconut-milk.png',
                                          'consistency': 'liquid',
                                          'name': 'full fat coconut milk',
                                          'original': '1 can full fat coconut milk (375 grams)',
                                          'originalString': '1 can full fat coconut milk (375 grams)',
                                          'originalName': 'can full fat coconut milk',
                                          'amount': 375.0,
                                          'unit': 'grams',
                                          'meta': ['canned'],
                                          'metaInformation': ['canned'],
                                          'measures': {'us': {'amount': 13.228,
                                                              'unitShort': 'oz',
                                                              'unitLong': 'ounces'},
                                                       'metric': {'amount': 375.0, 'unitShort': 'g', 'unitLong': 'grams'}}},
                                         {'id': 10014412,
                                          'aisle': 'Frozen',
                                          'image': 'ice-cubes.png',
                                          'consistency': 'solid',
                                          'name': 'ice',
                                          'original': '2-3 cups ice',
                                          'originalString': '2-3 cups ice',
                                          'originalName': 'ice',
                                          'amount': 2.0,
                                          'unit': 'cups',
                                          'meta': [],
                                          'metaInformation': [],
                                          'measures': {'us': {'amount': 2.0, 'unitShort': 'cups', 'unitLong': 'cups'},
                                                       'metric': {'amount': 473.176,
                                                                  'unitShort': 'ml',
                                                                  'unitLong': 'milliliters'}}},
                                         {'id': 93628,
                                          'aisle': 'Baking',
                                          'image': 'stevia.png',
                                          'consistency': 'solid',
                                          'name': 'stevia',
                                          'original': '½ teaspoon vanilla stevia',
                                          'originalString': '½ teaspoon vanilla stevia',
                                          'originalName': 'vanilla stevia',
                                          'amount': 0.5,
                                          'unit': 'teaspoon',
                                          'meta': [],
                                          'metaInformation': [],
                                          'measures': {'us': {'amount': 0.5,
                                                              'unitShort': 'tsps',
                                                              'unitLong': 'teaspoons'},
                                                       'metric': {'amount': 0.5, 'unitShort': 'tsps', 'unitLong': 'teaspoons'}}}],
                 'id': 800722,
                 'title': 'Keto Chocolate Smoothie',
                 'readyInMinutes': 45,
                 'servings': 2,
                 'sourceUrl': 'https://elanaspantry.com/keto-chocolate-smoothie/',
                 'image': 'https://spoonacular.com/recipeImages/800722-556x370.jpg',
                 'imageType': 'jpg',
                 'summary': 'You can never have too many morn meal recipes, so give Keto Chocolate Smoothie a try. For <b>$2.62 per serving</b>, this recipe <b>covers 19%</b> of your daily requirements of vitamins and minerals. This recipe makes 2 servings with <b>606 calories</b>, <b>15g of protein</b>, and <b>54g of fat</b> each. 212 people have tried and liked this recipe. If you have vanilla stevia, chocolate, egg-white protein powder, and a few other ingredients on hand, you can make it. It is brought to you by Elana\'s Pantry. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. It is a good option if you\'re following a <b>caveman, gluten free, dairy free, and primal</b> diet. Overall, this recipe earns a <b>good spoonacular score of 73%</b>. <a href="https://spoonacular.com/recipes/keto-chocolate-smoothie-803001">Keto Chocolate Smoothie</a>, <a href="https://spoonacular.com/recipes/green-keto-smoothie-with-avocado-and-mint-879795">Green Keto Smoothie with Avocado and Mint</a>, and <a href="https://spoonacular.com/recipes/keto-mint-chip-pudding-+-keto-clarity-608585">Keto Mint Chip Pudding + Keto Clarity</a> are very similar to this recipe.',
                 'cuisines': [],
                 'dishTypes': ['lunch', 'main course', 'main dish', 'dinner'],
                 'diets': ['gluten free',
                           'dairy free',
                           'paleolithic',
                           'lacto ovo vegetarian',
                           'primal',
                           'fodmap friendly',
                           'ketogenic'],
                 'occasions': [],
                 'instructions': 'In a vitamix, combine coconut milk, protein powder, chia, and steviaBlend in chocolate until smoothBlend in ice cubes until mixture is well combinedServe',
                 'analyzedInstructions': [{'name': '',
                                           'steps': [{'number': 1,
                                                      'step': 'In a vitamix, combine coconut milk, protein powder, chia, and stevia',
                                                      'ingredients': [{'id': 99239,
                                                                       'name': 'protein powder',
                                                                       'localizedName': 'protein powder',
                                                                       'image': 'plain-protein-powder.png'},
                                                                      {'id': 12118,
                                                                       'name': 'coconut milk',
                                                                       'localizedName': 'coconut milk',
                                                                       'image': 'coconut-milk.png'},
                                                                      {'id': 93628,
                                                                       'name': 'stevia',
                                                                       'localizedName': 'stevia',
                                                                       'image': 'stevia.png'}],
                                                      'equipment': []},
                                                     {'number': 2,
                                                      'step': 'Blend in chocolate until smooth',
                                                      'ingredients': [{'id': 19081,
                                                                       'name': 'chocolate',
                                                                       'localizedName': 'chocolate',
                                                                       'image': 'milk-chocolate.jpg'}],
                                                      'equipment': []},
                                                     {'number': 3,
                                                      'step': 'Blend in ice cubes until mixture is well combined',
                                                      'ingredients': [{'id': 10014412,
                                                                       'name': 'ice cubes',
                                                                       'localizedName': 'ice cubes',
                                                                       'image': 'ice-cubes.png'}],
                                                      'equipment': []},
                                                     {'number': 4, 'step': 'Serve', 'ingredients': [], 'equipment': []}]}],
                 'sourceName': None,
                 'creditsText': None,
                 'originalId': None}
