dictionary = {
    'q': 'keto',
    'from': 0,
    'to': 10,
    'more': True,
    'count': 607,
    'hits': [
        {
         'recipe': {'uri': 'http://www.edamam.com/ontologies/edamam.owl#recipe_8e29c4440cbd20e7296b8085f5771882',
                    'label': 'Keto Chocolate Smoothie recipes',
                    'image': 'https://www.edamam.com/web-img/083/0834f93ea42c9df7e2faf4125f2b13c1',
                    'source': "Elana's Pantry",
                    'url': 'https://elanaspantry.com/keto-chocolate-smoothie/',
                    'shareAs': 'http://www.edamam.com/recipe/keto-chocolate-smoothie-recipes-8e29c4440cbd20e7296b8085f5771882/keto',
                    'yield': 2.0,
                    'dietLabels': ['Low-Carb'],
                    'healthLabels': ['Vegetarian',
                                     'Peanut-Free',
                                     'Tree-Nut-Free',
                                     'Alcohol-Free'],
                    'cautions': ['Tree-Nuts', 'Sulfites'],
                    'ingredientLines': ['1 can full fat coconut milk (375 grams)',
                                        '¼ cup egg-white protein powder (20 grams)',
                                        '2 tablespoons ground chia seeds (20 grams)',
                                        '½ teaspoon vanilla stevia',
                                        '&frac13; cup chopped 85% dark chocolate (50 grams)',
                                        '2-3 cups ice'],
                    'ingredients': [{'text': '1 can full fat coconut milk (375 grams)',
                                     'weight': 375.0,
                                     'image': 'https://www.edamam.com/food-img/671/671f7528eadb1b01efb53243d0ef0f80.JPG'},
                                    {'text': '¼ cup egg-white protein powder (20 grams)',
                                     'weight': 20.0,
                                     'image': 'https://www.edamam.com/food-img/76a/76ab108398f84ad08fe841d3409ab70a.jpg'},
                                    {'text': '2 tablespoons ground chia seeds (20 grams)',
                                     'weight': 20.0,
                                     'image': 'https://www.edamam.com/food-img/bcc/bcc6e6bf3175772ad00b414636467257.jpg'},
                                    {'text': '½ teaspoon vanilla stevia',
                                     'weight': 2.0833333334390023,
                                     'image': 'https://www.edamam.com/food-img/b3f/b3f2a3fc27a8563cbabc38f55bc446ac.jpg'},
                                    {'text': '&frac13; cup chopped 85% dark chocolate (50 grams)',
                                     'weight': 50.0,
                                     'image': 'https://www.edamam.com/food-img/3cf/3cf0e13350f43392dc13c07d27ad145d.jpg'},
                                    {'text': '2-3 cups ice',
                                     'weight': 592.5,
                                     'image': 'https://www.edamam.com/food-img/5dd/5dd9d1361847b2ca53c4b19a8f92627e.jpg'}],
                    'calories': 1212.5500000000002,
                    'totalWeight': 1059.583333333439,
                    'totalTime': 10.0,
                    'totalNutrients': {'ENERC_KCAL': {'label': 'Energy',
                                                      'quantity': 1212.5500000000002,
                                                      'unit': 'kcal'},
                                       'FAT': {'label': 'Fat', 'quantity': 108.56249999999999, 'unit': 'g'},
                                       'FASAT': {'label': 'Saturated',
                                                 'quantity': 84.06394999999999,
                                                 'unit': 'g'},
                                       'FATRN': {'label': 'Trans',
                                                 'quantity': 0.043000000000000003,
                                                 'unit': 'g'},
                                       'FAMS': {'label': 'Monounsaturated', 'quantity': 10.46495, 'unit': 'g'},
                                       'FAPU': {'label': 'Polyunsaturated',
                                                'quantity': 6.775449999999999,
                                                'unit': 'g'},
                                       'CHOCDF': {'label': 'Carbs', 'quantity': 49.772833333438996, 'unit': 'g'},
                                       'FIBTG': {'label': 'Fiber', 'quantity': 13.670000000000002, 'unit': 'g'},
                                       'SUGAR': {'label': 'Sugars', 'quantity': 16.439, 'unit': 'g'},
                                       'SUGAR.added': {'label': 'Sugars, added',
                                                       'quantity': 11.995,
                                                       'unit': 'g'},
                                       'PROCNT': {'label': 'Protein', 'quantity': 25.89, 'unit': 'g'},
                                       'CHOLE': {'label': 'Cholesterol', 'quantity': 1.5, 'unit': 'mg'},
                                       'NA': {'label': 'Sodium', 'quantity': 232.24999999999997, 'unit': 'mg'},
                                       'CA': {'label': 'Calcium', 'quantity': 283.575, 'unit': 'mg'},
                                       'MG': {'label': 'Magnesium', 'quantity': 372.225, 'unit': 'mg'},
                                       'K': {'label': 'Potassium', 'quantity': 1450.5, 'unit': 'mg'},
                                       'FE': {'label': 'Iron', 'quantity': 22.269, 'unit': 'mg'},
                                       'ZN': {'label': 'Zinc', 'quantity': 6.05025, 'unit': 'mg'},
                                       'P': {'label': 'Phosphorus', 'quantity': 940.4, 'unit': 'mg'},
                                       'VITA_RAE': {'label': 'Vitamin A', 'quantity': 1.0, 'unit': 'µg'},
                                       'VITC': {'label': 'Vitamin C', 'quantity': 4.07, 'unit': 'mg'},
                                       'THIA': {'label': 'Thiamin (B1)', 'quantity': 0.2811, 'unit': 'mg'},
                                       'RIBF': {'label': 'Riboflavin (B2)', 'quantity': 0.1058, 'unit': 'mg'},
                                       'NIA': {'label': 'Niacin (B3)', 'quantity': 5.15315, 'unit': 'mg'},
                                       'VITB6A': {'label': 'Vitamin B6', 'quantity': 0.1568, 'unit': 'mg'},
                                       'FOLDFE': {'label': 'Folate equivalent (total)',
                                                  'quantity': 110.30000000000001,
                                                  'unit': 'µg'},
                                       'FOLFD': {'label': 'Folate (food)',
                                                 'quantity': 120.10000000000001,
                                                 'unit': 'µg'},
                                       'FOLAC': {'label': 'Folic acid', 'quantity': 0.0, 'unit': 'µg'},
                                       'VITB12': {'label': 'Vitamin B12', 'quantity': 0.14, 'unit': 'µg'},
                                       'VITD': {'label': 'Vitamin D', 'quantity': 0.0, 'unit': 'µg'},
                                       'TOCPHA': {'label': 'Vitamin E', 'quantity': 0.395, 'unit': 'mg'},
                                       'VITK1': {'label': 'Vitamin K', 'quantity': 3.65, 'unit': 'µg'},
                                       'WATER': {'label': 'Water', 'quantity': 867.8785, 'unit': 'g'}},
                    'totalDaily': {'ENERC_KCAL': {'label': 'Energy',
                                                  'quantity': 60.627500000000005,
                                                  'unit': '%'},
                                   'FAT': {'label': 'Fat', 'quantity': 167.01923076923075, 'unit': '%'},
                                   'FASAT': {'label': 'Saturated',
                                             'quantity': 420.31974999999994,
                                             'unit': '%'},
                                   'CHOCDF': {'label': 'Carbs', 'quantity': 16.590944444479664, 'unit': '%'},
                                   'FIBTG': {'label': 'Fiber', 'quantity': 54.68000000000001, 'unit': '%'},
                                   'PROCNT': {'label': 'Protein', 'quantity': 51.78, 'unit': '%'},
                                   'CHOLE': {'label': 'Cholesterol', 'quantity': 0.5, 'unit': '%'},
                                   'NA': {'label': 'Sodium', 'quantity': 9.677083333333332, 'unit': '%'},
                                   'CA': {'label': 'Calcium', 'quantity': 28.3575, 'unit': '%'},
                                   'MG': {'label': 'Magnesium', 'quantity': 88.625, 'unit': '%'},
                                   'K': {'label': 'Potassium', 'quantity': 30.861702127659573, 'unit': '%'},
                                   'FE': {'label': 'Iron', 'quantity': 123.71666666666664, 'unit': '%'},
                                   'ZN': {'label': 'Zinc', 'quantity': 55.002272727272725, 'unit': '%'},
                                   'P': {'label': 'Phosphorus', 'quantity': 134.34285714285716, 'unit': '%'},
                                   'VITA_RAE': {'label': 'Vitamin A',
                                                'quantity': 0.1111111111111111,
                                                'unit': '%'},
                                   'VITC': {'label': 'Vitamin C',
                                            'quantity': 4.522222222222222,
                                            'unit': '%'},
                                   'THIA': {'label': 'Thiamin (B1)',
                                            'quantity': 23.425000000000004,
                                            'unit': '%'},
                                   'RIBF': {'label': 'Riboflavin (B2)',
                                            'quantity': 8.138461538461538,
                                            'unit': '%'},
                                   'NIA': {'label': 'Niacin (B3)', 'quantity': 32.2071875, 'unit': '%'},
                                   'VITB6A': {'label': 'Vitamin B6',
                                              'quantity': 12.061538461538461,
                                              'unit': '%'},
                                   'FOLDFE': {'label': 'Folate equivalent (total)',
                                              'quantity': 27.575000000000003,
                                              'unit': '%'},
                                   'VITB12': {'label': 'Vitamin B12',
                                              'quantity': 5.833333333333334,
                                              'unit': '%'},
                                   'VITD': {'label': 'Vitamin D', 'quantity': 0.0, 'unit': '%'},
                                   'TOCPHA': {'label': 'Vitamin E',
                                              'quantity': 2.6333333333333333,
                                              'unit': '%'},
                                   'VITK1': {'label': 'Vitamin K',
                                             'quantity': 3.0416666666666665,
                                             'unit': '%'}},
                    'digest': [{'label': 'Fat',
                                'tag': 'FAT',
                                'schemaOrgTag': 'fatContent',
                                'total': 108.56249999999999,
                                'hasRDI': True,
                                'daily': 167.01923076923075,
                                'unit': 'g',
                                'sub': [{'label': 'Saturated',
                                         'tag': 'FASAT',
                                         'schemaOrgTag': 'saturatedFatContent',
                                         'total': 84.06394999999999,
                                         'hasRDI': True,
                                         'daily': 420.31974999999994,
                                         'unit': 'g'},
                                        {'label': 'Trans',
                                         'tag': 'FATRN',
                                         'schemaOrgTag': 'transFatContent',
                                         'total': 0.043000000000000003,
                                         'hasRDI': False,
                                         'daily': 0.0,
                                         'unit': 'g'},
                                        {'label': 'Monounsaturated',
                                         'tag': 'FAMS',
                                         'schemaOrgTag': None,
                                         'total': 10.46495,
                                         'hasRDI': False,
                                         'daily': 0.0,
                                         'unit': 'g'},
                                        {'label': 'Polyunsaturated',
                                         'tag': 'FAPU',
                                         'schemaOrgTag': None,
                                         'total': 6.775449999999999,
                                         'hasRDI': False,
                                         'daily': 0.0,
                                         'unit': 'g'}]},
                               {'label': 'Carbs',
                                'tag': 'CHOCDF',
                                'schemaOrgTag': 'carbohydrateContent',
                                'total': 49.772833333438996,
                                'hasRDI': True,
                                'daily': 16.590944444479664,
                                'unit': 'g',
                                'sub': [{'label': 'Carbs (net)',
                                         'tag': 'CHOCDF.net',
                                         'schemaOrgTag': None,
                                         'total': 36.102833333438994,
                                         'hasRDI': False,
                                         'daily': 0.0,
                                         'unit': 'g'},
                                        {'label': 'Fiber',
                                         'tag': 'FIBTG',
                                         'schemaOrgTag': 'fiberContent',
                                         'total': 13.670000000000002,
                                         'hasRDI': True,
                                         'daily': 54.68000000000001,
                                         'unit': 'g'},
                                        {'label': 'Sugars',
                                         'tag': 'SUGAR',
                                         'schemaOrgTag': 'sugarContent',
                                         'total': 16.439,
                                         'hasRDI': False,
                                         'daily': 0.0,
                                         'unit': 'g'},
                                        {'label': 'Sugars, added',
                                         'tag': 'SUGAR.added',
                                         'schemaOrgTag': None,
                                         'total': 11.995,
                                         'hasRDI': False,
                                         'daily': 0.0,
                                         'unit': 'g'}]},
                               {'label': 'Protein',
                                'tag': 'PROCNT',
                                'schemaOrgTag': 'proteinContent',
                                'total': 25.89,
                                'hasRDI': True,
                                'daily': 51.78,
                                'unit': 'g'},
                               {'label': 'Cholesterol',
                                'tag': 'CHOLE',
                                'schemaOrgTag': 'cholesterolContent',
                                'total': 1.5,
                                'hasRDI': True,
                                'daily': 0.5,
                                'unit': 'mg'},
                               {'label': 'Sodium',
                                'tag': 'NA',
                                'schemaOrgTag': 'sodiumContent',
                                'total': 232.24999999999997,
                                'hasRDI': True,
                                'daily': 9.677083333333332,
                                'unit': 'mg'},
                               {'label': 'Calcium',
                                'tag': 'CA',
                                'schemaOrgTag': None,
                                'total': 283.575,
                                'hasRDI': True,
                                'daily': 28.3575,
                                'unit': 'mg'},
                               {'label': 'Magnesium',
                                'tag': 'MG',
                                'schemaOrgTag': None,
                                'total': 372.225,
                                'hasRDI': True,
                                'daily': 88.625,
                                'unit': 'mg'},
                               {'label': 'Potassium',
                                'tag': 'K',
                                'schemaOrgTag': None,
                                'total': 1450.5,
                                'hasRDI': True,
                                'daily': 30.861702127659573,
                                'unit': 'mg'},
                               {'label': 'Iron',
                                'tag': 'FE',
                                'schemaOrgTag': None,
                                'total': 22.269,
                                'hasRDI': True,
                                'daily': 123.71666666666664,
                                'unit': 'mg'},
                               {'label': 'Zinc',
                                'tag': 'ZN',
                                'schemaOrgTag': None,
                                'total': 6.05025,
                                'hasRDI': True,
                                'daily': 55.002272727272725,
                                'unit': 'mg'},
                               {'label': 'Phosphorus',
                                'tag': 'P',
                                'schemaOrgTag': None,
                                'total': 940.4,
                                'hasRDI': True,
                                'daily': 134.34285714285716,
                                'unit': 'mg'},
                               {'label': 'Vitamin A',
                                'tag': 'VITA_RAE',
                                'schemaOrgTag': None,
                                'total': 1.0,
                                'hasRDI': True,
                                'daily': 0.1111111111111111,
                                'unit': 'µg'},
                               {'label': 'Vitamin C',
                                'tag': 'VITC',
                                'schemaOrgTag': None,
                                'total': 4.07,
                                'hasRDI': True,
                                'daily': 4.522222222222222,
                                'unit': 'mg'},
                               {'label': 'Thiamin (B1)',
                                'tag': 'THIA',
                                'schemaOrgTag': None,
                                'total': 0.2811,
                                'hasRDI': True,
                                'daily': 23.425000000000004,
                                'unit': 'mg'},
                               {'label': 'Riboflavin (B2)',
                                'tag': 'RIBF',
                                'schemaOrgTag': None,
                                'total': 0.1058,
                                'hasRDI': True,
                                'daily': 8.138461538461538,
                                'unit': 'mg'},
                               {'label': 'Niacin (B3)',
                                'tag': 'NIA',
                                'schemaOrgTag': None,
                                'total': 5.15315,
                                'hasRDI': True,
                                'daily': 32.2071875,
                                'unit': 'mg'},
                               {'label': 'Vitamin B6',
                                'tag': 'VITB6A',
                                'schemaOrgTag': None,
                                'total': 0.1568,
                                'hasRDI': True,
                                'daily': 12.061538461538461,
                                'unit': 'mg'},
                               {'label': 'Folate equivalent (total)',
                                'tag': 'FOLDFE',
                                'schemaOrgTag': None,
                                'total': 110.30000000000001,
                                'hasRDI': True,
                                'daily': 27.575000000000003,
                                'unit': 'µg'},
                               {'label': 'Folate (food)',
                                'tag': 'FOLFD',
                                'schemaOrgTag': None,
                                'total': 120.10000000000001,
                                'hasRDI': False,
                                'daily': 0.0,
                                'unit': 'µg'},
                               {'label': 'Folic acid',
                                'tag': 'FOLAC',
                                'schemaOrgTag': None,
                                'total': 0.0,
                                'hasRDI': False,
                                'daily': 0.0,
                                'unit': 'µg'},
                               {'label': 'Vitamin B12',
                                'tag': 'VITB12',
                                'schemaOrgTag': None,
                                'total': 0.14,
                                'hasRDI': True,
                                'daily': 5.833333333333334,
                                'unit': 'µg'},
                               {'label': 'Vitamin D',
                                'tag': 'VITD',
                                'schemaOrgTag': None,
                                'total': 0.0,
                                'hasRDI': True,
                                'daily': 0.0,
                                'unit': 'µg'},
                               {'label': 'Vitamin E',
                                'tag': 'TOCPHA',
                                'schemaOrgTag': None,
                                'total': 0.395,
                                'hasRDI': True,
                                'daily': 2.6333333333333333,
                                'unit': 'mg'},
                               {'label': 'Vitamin K',
                                'tag': 'VITK1',
                                'schemaOrgTag': None,
                                'total': 3.65,
                                'hasRDI': True,
                                'daily': 3.0416666666666665,
                                'unit': 'µg'},
                               {'label': 'Sugar alcohols',
                                'tag': 'Sugar.alcohol',
                                'schemaOrgTag': None,
                                'total': 0.0,
                                'hasRDI': False,
                                'daily': 0.0,
                                'unit': 'g'},
                               {'label': 'Water',
                                'tag': 'WATER',
                                'schemaOrgTag': None,
                                'total': 867.8785,
                                'hasRDI': False,
                                'daily': 0.0,
                                'unit': 'g'}]},
         'bookmarked': False,
         'bought': False}

    ],
    'bookmarked': False,
    'bought': False
}
